### ISSUE TITLE
model performance

### ISSUE THREAD

**Issue by natxopedreira** [salmanoglubatuhan/detectron2-faster-rcnn-with-stanford-dataset#1]
Hello

Can you comment how is the performance with detectron2? im training a model with retinanet and im curious about performance of detectron

Thanks

**Comment by salmanoglubatuhan** [comment]
In this project performance is not good enough, Stanford dataset has some problem with annotations. Although, detectron is usable and powerfull with good dataset so you should try detectron.

**Comment by natxopedreira** [comment]
Thank you!! will test it
